name: Release draft tsterm
on:
  workflow_dispatch:
    inputs:
      RELEASE_NUMBER:
        description: 'Specify a semver pattern (without v).'
        required: true
      RUN_ID:
        description: 'Specify run id of asset to associate with release.'
        reqiured: false

#permissions:
#  contents: write
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: '[Download] Default'
        if: ${{ inputs.RUN_ID == '' }}
        run: gh run download $(gh run list -w "Build tsterm" --json databaseId -q .[0].databaseId)
      - name: '[Download] Input'
        if: ${{ inputs.RUN_ID }}
        run: gh run download ${{ inputs.RUN_ID }}
      - name: '[Create release]'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.RELEASE_NUMBER }}
          name: Release v${{ inputs.RELEASE_NUMBER }}
          draft: true
          prerelease: false
          #body_path: CHANGELOG.md
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: tsterm/*
#      - name: '[Create release]'
#        id: create_release
#        uses: actions/create-release@v1
#        with:
#          tag_name: v${{ inputs.RELEASE_NUMBER }}
#          release_name: Release v${{ inputs.RELEASE_NUMBER }}
#          draft: true
#          prerelease: false
#      - name: '[Upload]'
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
          
          
